AWSTemplateFormatVersion: 2010-09-09
Description: |
  Resources for deploying the cloud native honeypot
Parameters:
  VpcId:
    AllowedPattern: ".+" # Makes it Required
    Description: The VPC to place the honeypot service in
    Type: String

  SubnetId:
    AllowedPattern: ".+" # Makes it Required
    Description: The subnet to place the honeypot service in
    Type: String

# Metadata:

# Mappings:

# Conditions:

Resources:
  # TODO - allow for injecting an ECS cluster identifier instead

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      Tags:
        - Key: cloud-native-honeypot
          Value: true

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref SGIngressFullAccess
          Subnets:
            - !Ref SubnetId
      PlatformVersion: 1.4.0
      PropagateTags: SERVICE
      Tags:
        - Key: cloud-native-honeypot
          Value: true
      TaskDefinition: "String" # TODO - fill out the task definition here

  SGIngressFullAccess:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows all ingress traffic from within the VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0 # Allow anything in the VPC to hit the honeypot
          IpProtocol: -1
      Tags:
        - Key: cloud-native-honeypot
          Value: true
      VpcId: !Ref VpcId
# Transform:

# Outputs:
