AWSTemplateFormatVersion: 2010-09-09
Description: |
  Resources for deploying the cloud native honeypot
Parameters:
  VpcId:
    AllowedPattern: ".+" # Makes it Required
    Description: The VPC to place the honeypot service in
    Type: String

  SubnetId:
    AllowedPattern: ".+" # Makes it Required
    Description: The subnet to place the honeypot service in
    Type: String

# Metadata:

# Mappings:

# Conditions:

Resources:
  # TODO - allow for injecting an ECS cluster identifier instead

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      Tags:
        - Key: cloud-native-honeypot
          Value: true

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref SGIngressFullAccess
          Subnets:
            - !Ref SubnetId
      PlatformVersion: 1.4.0
      PropagateTags: SERVICE
      Tags:
        - Key: cloud-native-honeypot
          Value: true
      TaskDefinition: !Ref TaskDefinition

  SGIngressFullAccess:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows all ingress traffic from within the VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0 # Allow anything in the VPC to hit the honeypot
          IpProtocol: -1
      Tags:
        - Key: cloud-native-honeypot
          Value: true
      VpcId: !Ref VpcId

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Command: String
          Environment:
            - Name: ENABLE_SERVER_SIMPLE_HTTP
              Value: true
          HealthCheck: # TODO - see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-healthcheck.html
          Image: ghcr.io/grunet/cloud-native-honeypot:v0.4.2
          LogConfiguration: # TODO - see https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html this will involve the custom log group
          Name: cloud-native-honeypot
          PortMappings:
            - ContainerPort: 8000
          ReadonlyRootFilesystem: true
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: # TODO - fill this out
      Family: cloud-native-honeypot # TODO - review if this is appropriate
      NetworkMode: awsvpc
      Tags:
        - Key: cloud-native-honeypot
          Value: true
      TaskRoleArn: # TODO - fill this out

# Transform:

# Outputs:
