[tool.poetry]
name = "honeypot"
version = "0.0.0" # Tracked in version.json instead
description = "Source code for the honeypot images"
authors = ["Grunet"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
flake8 = "^6.0.0"
pyre-check = "^0.9.18"
mypy = "^1.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
