name: Check for Updated Dependencies
on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight
  workflow_dispatch:

# Note: I should receive an email notification when this workflow fails since I last modified it and the cron. Can generalize as needed (e.g. to creating a Github issue)

jobs:
  chainguard-images:
    runs-on: ubuntu-22.04
    steps:
      - name: Check overview page
        run: |
          curl https://edu.chainguard.dev/chainguard/chainguard-images/reference/python/overview/ | grep sha256:6e512c60467cb53572112d8b5f1200d93cc7f883db01e57836fd93754f6bb4e8

      # If this fails, that likely means the "latest" and "latest-dev" tags for Python are pointing at new images with new digests
      # Follow the process to update the Dockerfiles accordingly, then update the hardcoded digest here to be one of the new digests (doesn't matter which one) to detect future changes

  fargate-platform-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Check platform versions page
        run: |
          ! curl https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform-linux-fargate.html | grep 1.4.1
          ! curl https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform-linux-fargate.html | grep 1.5.0
          ! curl https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform-linux-fargate.html | grep 2.0.0

      # If this fails, that likely means there's a new platform version for Fargate available
      # Follow the process to update the templates accordingly, then update the versions here to the next possible patch, minor, and major versions
