name: CI
on: [push]
jobs:
  honeypot:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: packages/honeypot/
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

        # Adapted from https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install poetry
        run: |
          pipx install poetry==1.5.1
      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: "3.11.4"
          cache: "poetry"
      - run: |
          poetry install

      - name: Check Formatting
        run: |
          make check-format

      - name: Lint
        run: |
          make lint

      - name: Static Analysis - pyre
        run: |
          make static-analysis-pyre

      - name: Static Analysis - mypy
        run: |
          make static-analysis-mypy

      - name: Unit Tests
        run: |
          make test-unit

      - name: Check Docker Version
        # Make sure the version of Docker doesn't unexpectedly change and doesn't drift much from what's used in Codespaces
        # If this change looks legitimate (i.e. Github updating the vendored version, or coming after a change to the runner OS version) update the hard-coded version below
        run: |
          docker --version
          docker --version | grep "Docker version 20.10.25+azure-2"

      - name: Smoke Tests - Server Startup
        run: |
          make start-docker-simple-http

      - name: Smoke Tests - Health Check
        run: |
          sleep 5
          curl --fail http://127.0.0.1:8000/healthcheck

      - name: Smoke Tests - Server Shutdown
        run: |
          make stop-docker-simple-http

  aws-cloudformation:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: packages/aws-cloudformation/
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Check pip version
        # Make sure the version of pip doesn't unexpectedly change and doesn't drift much from what's used in Codespaces
        # If this change looks legitimate (i.e. Github updating the vendored version, or coming after a change to the runner OS version) update the hard-coded version below
        run: |
          pip --version
          pip --version | grep "22.0.2"

      - name: Install cfn-lint
        run: |
          pip install cfn-lint=='0.79.5'

      - name: Lint
        run: |
          make lint
