name: CI
on: [push]
jobs:
  honeypot:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: packages/honeypot/
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

        # Adapted from https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install poetry
        run: | 
          pipx install poetry==1.5.1
      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: '3.11.4'
          cache: 'poetry'
      - run: | 
          poetry install

      - name: Check Formatting
        run: |
          make check-format

      - name: Lint
        run: |
          make lint
